version: '3.7'

services:
    client:
        container_name: client
        build: 
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
    
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - './server:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development